spring.datasource.url=jdbc:mysql://localhost:3306/mi_app_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ESTO ES LO MÁS IMPORTANTE PARA QUITAR TU ERROR:
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Evita que Hibernate intente leer metadatos raros que causan el error 'RESERVED'
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false